-- Add a per-subscription webhook signing secret.
--
-- The webhook-dispatcher uses this to compute HMAC-SHA256(secret, body) and
-- sets it on the X-AnyHook-Signature header so receivers can verify that a
-- delivery actually originated from AnyHook.
--
-- Existing rows get a random hex backfill via gen_random_bytes (pgcrypto).
-- New rows get a secret generated by the application layer.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE subscriptions
    ADD COLUMN webhook_secret TEXT NOT NULL
    DEFAULT encode(gen_random_bytes(32), 'hex');

-- Drop the default so future inserts MUST provide a value (the API does).
-- This guarantees no two subscriptions share a secret due to a default.
ALTER TABLE subscriptions ALTER COLUMN webhook_secret DROP DEFAULT;
